# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  pod 'TensorFlowLite', '1.12.0'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end